### PR TITLE
Help messages on cli displays subcommands names

### LINKED ISSUE #623: --help options does not work correctly for some subcommands
`hanami new --help`, instead of describing available options, prints

```
ERROR: "hanami new" was called with no arguments
Usage: "hanami new APPLICATION_NAME"
```

This discovery made me try the `--help` option for all other subcommands (at least those listed by `hanami help`). This way I found a bug
- `hanami db --help`
- `hanami destroy --help`
- `hanami generate --help`

All these commands print

```
Usage:
  hanami help [COMMAND]

Describe subcommands or one specific subcommand
```

which is help for `hanami help`, not for the respective subcommands.

**(ADDED LATER)**

Help for sub-subcommands prints misleading usage synopsis: e.g. `hanami db create --help` prints

```
Usage:
  hanami create
```

instead of expected

```
Usage:
  hanami db create
```

### PR DESCRIPTION
**Pull request by docStonehenge**
Fixes #623 

TODO:

- [x] Prints subcommands correct usage synopsis

- [x] Prints correct error message for commands called without arguments, e.g.: "hanami destroy model"

### CODE REVIEW

File: lib/hanami/cli_base.rb [hunk 1]
```diff
@@ -27,5 +27,20 @@ module CliBase
     def define_commands(&blk)
       class_eval(&blk) if block_given?
     end
+
+    def banner(command, nspace = true, subcommand = false)
+      super(command, nspace, namespace != 'hanami:cli')
+    end
+
+    def handle_argument_error(command, error, args, arity)
```
Comment (docStonehenge) [inline lib/hanami/cli_base.rb]: @jodosha This is necessary due to a [bug](https://github.com/erikhuda/thor/pull/464) on Thor. We should probably remove after the new version release.

[thor/base.rb#L479](https://github.com/erikhuda/thor/blob/v0.19.4/lib/thor/base.rb#L479) doesn't consider subcommand names to build error messages

**Comment by jodosha** [comment]
@docStonehenge Thank you for this PR. Just merged it!
