### PR TITLE
Generate empty `lib/<project-name>.rb` file

### LINKED ISSUE #758: `Hanami::Utils.reload!` is used in development regardless if code-reloading is used or not.
I found subj while using `Dry::Struct` for one of my entities. Latter one does not plays well when double loaded with `load` leading to `Dry::Struct::RepeatedAttributeError` exception being raised:

```
>>= bundle exec hanami c
bundler: failed to load command: hanami (/home/ixti/.gem/ruby/2.4.0/bin/hanami)
Dry::Struct::RepeatedAttributeError: Attribute :id has already been defined
  /home/ixti/.gem/ruby/2.4.0/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:56:in `check_schema_duplication'
  /home/ixti/.gem/ruby/2.4.0/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:40:in `attributes'
  /home/ixti/.gem/ruby/2.4.0/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:36:in `attribute'
  /home/ixti/playing-with-hanami/example/lib/example/entities/access_token.rb:8:in `<class:AccessToken>'
  /home/ixti/playing-with-hanami/example/lib/example/entities/access_token.rb:3:in `<top (required)>'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `load'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `block in reload!'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:90:in `each'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:90:in `for_each_file_in'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-utils-1.0.0.beta3/lib/hanami/utils.rb:68:in `reload!'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components/components.rb:59:in `block (2 levels) in <module:Components>'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:40:in `call'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:83:in `block in resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `each'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:138:in `resolve_requirements'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components/component.rb:36:in `call'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
  /home/ixti/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:83:in `block in resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `each'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/components.rb:82:in `resolve'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/commands/command.rb:57:in `initialize'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/commands/console.rb:52:in `initialize'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/cli.rb:89:in `new'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/lib/hanami/cli.rb:89:in `console'
  /home/ixti/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /home/ixti/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/ixti/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/ixti/.gem/ruby/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/ixti/.gem/ruby/2.4.0/gems/hanami-1.0.0.beta3/bin/hanami:5:in `<top (required)>'
  /home/ixti/.gem/ruby/2.4.0/bin/hanami:22:in `load'
  /home/ixti/.gem/ruby/2.4.0/bin/hanami:22:in `<top (required)>'
```

I wasn't able to receive any replies in dry-rb chat if it's possible to disable attributes schema checks. Although from my investigation of dry-struct code it's impossible. I believe that hanami should provide a way to explicitly disable code reloading everywhere (thus `require` will be used all the time, not `load`) not only for server but for console and everything else as well.

### PR DESCRIPTION
**Pull request by jodosha**
This PR implements [a suggested solution](https://github.com/hanami/hanami/issues/758#issuecomment-290316265) to fix #758 

/cc @ixti and @hanami/core for review.

### CODE REVIEW

File: spec/support/shared_examples/cli/new.rb [hunk 1]
```diff
@@ -44,7 +44,6 @@
       # lib/<project>.rb
       #
       expect("lib/#{project}.rb").to have_file_content <<-END
```
Comment (cllns) [inline spec/support/shared_examples/cli/new.rb]: can this be changed to just `""` (or `"\n"?`) instead of using the HEREDOC?

Also, do we need this file at all, if it's blank? If so, could we put a comment in here saying something like 
```ruby
# This file is intentionally blank.
```

Comment (jodosha) [inline spec/support/shared_examples/cli/new.rb]: @cllns Yeah, I'm gonna switch from HEREDOC to simpler string representation.

I was thinking to define a blank module like:

```ruby
module Bookshelf
end
```

Comment (ixti) [inline spec/support/shared_examples/cli/new.rb]: Ohh. I like this! (empty module)

Comment (cllns) [inline spec/support/shared_examples/cli/new.rb]: I like an empty module too :)

Comment (davydovanton) [inline spec/support/shared_examples/cli/new.rb]: Good idea with the empty module 👍 
Maybe we also add the comment with this PR? I'm sure that some developers will have questions about this module in future.

**Comment by ixti** [comment]
Just to confirm. This fixes #758 for me :D
