### PR TITLE
Exit with status code if rake command was raised

### LINKED ISSUE #549: Exit in case a Rake tasks fails
## Background

Each Hanami project ships with a couple of "standard" Rake tasks. These tasks are `db:migrate` and `assets:precompile`. We support them, because of Rails influence in SaaS world. Heroku runs them automatically for all the Ruby (not Rails) apps.

Read more at: http://hanamirb.org/guides/applications/rake/

## Enhancement

We should exit the parent process in case the Rake task fails.

---

Thanks to @thhermansen for suggesting this.

### PR DESCRIPTION
**Pull request by davydovanton**
Fixed #549

/cc @hanami/core-team

### CODE REVIEW

File: test/rake_helper_test.rb [hunk 1]
```diff
@@ -30,6 +30,20 @@
     end
   end
 
+  describe 'when "db:migrate" task failed' do
+    it 'exits with failde status code' do
```
Comment (joneslee85) [inline test/rake_helper_test.rb]: s/failde/failed

**Comment by jodosha** [comment]
I manually tested it and it works. Thanks @davydovanton :+1: 

Steps to reproduce:

```shell
➜ hanami new bookshelf --hanami-head=true
➜ cd bookshelf
➜ vim Gemfile # edit: `gem 'hanami', github: 'davydovanton/lotus', branch: 'rake-exit'
➜ bundle
➜ HANAMI_ENV=production bundle exec rake db:migrate # this should raise an error
➜ echo $? # => 1
```

**Comment by davydovanton** [comment]
thanks for merge :+1:
