### PR TITLE
Fix model generation for camelcased app name

### LINKED ISSUE #490: Different in behavior of 'hanami new' and 'hanami generate model'
I found difference in behavior of `hanami new` and `hanami generate model` when appname includes capital letters.

For example,  `MyProject/lib` directory is as following after I ran `hanami new MyProject`

```
MyProject/lib/
  - config/
  - myproject/
  - myproject.rb
```

And it is as following after I ran `hanami generate model model`

```
MyProject/lib/
  - config/
  - myproject/
  - MyProject/
      - repositories/model.rb
      - entities/model.rb
  - myproject.rb
```

There is `Dir["#{ __dir__ }/investgate/**/*.rb"].each { |file| require_relative file }` in `myproject.rb`. So, Model won't loaded.

### PR DESCRIPTION
**Pull request by davydovanton**
Fixed #490

### CODE REVIEW

**Comment by zakuro9715** [comment]
Why don't we use ApplicationName?

`hanami new` command uses ApplicationName.
https://github.com/hanami/hanami/blob/master/lib/hanami/commands/new/abstract.rb#L67-L73

I think we might want to use ApplicationName like `hanami new` for model generation.

File: lib/hanami/commands/generate/model.rb [hunk 1]
```diff
@@ -57,7 +57,7 @@ def model_name_valid
         end
 
         def model_root
-          Pathname.new('lib').join(::File.basename(Dir.getwd))
+          Pathname.new('lib').join(app_name_downcased)
```
Comment (joneslee85) [inline lib/hanami/commands/generate/model.rb]: what do you think about renaming it to `app_name` instead?

File: test/commands/generate/model_test.rb [hunk 2]
```diff
@@ -33,7 +33,16 @@
...
       end
     end
+  end
 
+  describe 'sanitizes application name' do
+    it 'downcases it' do
+      with_temp_dir('TestApp') do |original_wd|
+        command = Hanami::Commands::Generate::Model.new({}, 'car')
+        capture_io { command.start }
+        assert_generated_file(original_wd.join('test/fixtures/commands/generate/model/car.rb'), 'lib/testapp/entities/car.rb')
```
Comment (joneslee85) [inline test/commands/generate/model_test.rb]: I don't think `testapp` is the right application name for `TestApp`, I'd prefer it follows the same naming convention of Ruby, that is `test_app`.

Comment (davydovanton) [inline test/commands/generate/model_test.rb]: I don't know because hanami generate `testapp.rb` db config file. @jodosha what do you think?

File: lib/hanami/commands/generate/model.rb (hunk 1 above)
Comment (davydovanton) [inline lib/hanami/commands/generate/model.rb]: yep, I like it :+1:

File: test/commands/generate/model_test.rb (hunk 2 above)
Comment (jodosha) [inline test/commands/generate/model_test.rb]: :+1: For @joneslee85 suggestion.
